acquisition:
  criterion_name: image_acquisition
  extended_resolution: true
  image_name: image_acquisition
  imaging_enabled: true
  resolution_threshold: 1
  sputter: false
  sputter_grid: 1
  wd_correction: 1.0e-08
  y_correction: 0
autofunction:
- autofunction: StepAutoFunction
  criterion_name: working_distance - poke
  delta_x: 0
  execute_resolution: 0
  execute_slices: 0
  image_name: working_distance - poke
  keep_trying: false
  mask_name: none
  max_attempts: 8
  min_diff: 0.005
  name: working_distance - poke
  sweeping_range:
  - -7.0e-07
  - 7.0e-07
  sweeping_steps: 2
  sweeping_strategy: BasicInterleavedSweeping
  sweeping_total_cycles: 1
  variable: electron_beam.working_distance
- autofunction: StepAutoFunction
  criterion_name: stigX - poke
  delta_x: 0
  execute_resolution: 0
  execute_slices: 0
  image_name: stigX - poke
  keep_trying: false
  mask_name: none
  max_attempts: 8
  min_diff: 0.005
  name: stigX - poke
  sweeping_range:
  - -0.035
  - 0.035
  sweeping_steps: 2
  sweeping_strategy: BasicInterleavedSweeping
  sweeping_total_cycles: 1
  variable: electron_beam.stigmator_x
- autofunction: StepAutoFunction
  criterion_name: stigY - poke
  delta_x: 0
  execute_resolution: 0
  execute_slices: 0
  image_name: stigY - poke
  keep_trying: false
  mask_name: none
  max_attempts: 8
  min_diff: 0.005
  name: stigY - poke
  sweeping_range:
  - -0.035
  - 0.035
  sweeping_steps: 2
  sweeping_strategy: BasicInterleavedSweeping
  sweeping_total_cycles: 1
  variable: electron_beam.stigmator_y
- autofunction: StepAutoFunction
  criterion_name: laX - poke
  delta_x: 0
  execute_resolution: 0
  execute_slices: 0
  image_name: laX - poke
  keep_trying: false
  mask_name: none
  max_attempts: 8
  min_diff: 0.005
  name: laX - poke
  sweeping_range: &id001
  - -2.0e-05
  - 2.0e-05
  sweeping_steps: 2
  sweeping_strategy: BasicInterleavedSweeping
  sweeping_total_cycles: 1
  variable: electron_beam.lens_alignment_x
- autofunction: StepAutoFunction
  criterion_name: laY - poke
  delta_x: 0
  execute_resolution: 0
  execute_slices: 0
  image_name: laY - poke
  keep_trying: false
  mask_name: none
  max_attempts: 8
  min_diff: 0.005
  name: laY - poke
  sweeping_range: *id001
  sweeping_steps: 2
  sweeping_strategy: BasicInterleavedSweeping
  sweeping_total_cycles: 1
  variable: electron_beam.lens_alignment_y
- autofunction: ManufacturerAutoFunction
  criterion_name: lens_align - TFS_pre
  delta_x: 3.8e-05
  execute_resolution: 0
  execute_slices: 0
  image_name: lens_align - TFS_pre
  mask_name: none
  max_attempts: 8
  name: lens_align - TFS_pre
  variable: electron_beam.lens_alignment
- autofunction: ManufacturerAutoFunction
  criterion_name: working_distance - TFS2
  delta_x: 3.8e-05
  execute_resolution: 0
  execute_slices: 0
  image_name: working_distance - TFS2
  mask_name: none
  max_attempts: 800000
  name: working_distance - TFS2
  variable: electron_beam.working_distance
- autofunction: ManufacturerAutoFunction
  criterion_name: lens_align - TFS
  delta_x: 2.5e-05
  execute_resolution: 0
  execute_slices: 20
  image_name: lens_align - TFS
  mask_name: none
  max_attempts: 800000
  name: lens_align - TFS
  resolution: 6144x4096
  variable: electron_beam.lens_alignment
- autofunction: ManufacturerAutoFunction
  criterion_name: stigmator - TFS
  delta_x: 2.5e-05
  execute_resolution: 0
  execute_slices: 20
  horizontal_field_width: 6.91e-06
  image_name: stigmator - TFS
  mask_name: none
  max_attempts: 800000
  name: stigmator - TFS
  resolution: 6144x4096
  variable: electron_beam.stigmator
- autofunction: ManufacturerAutoFunction
  criterion_name: source_tilt - TFS
  delta_x: 0
  execute_resolution: 0
  execute_slices: 100
  image_name: source_tilt - TFS
  mask_name: none
  max_attempts: 8
  name: source_tilt - TFS
  variable: electron_beam.source_tilt
- autofunction: AutoFunction
  criterion_name: working_distance - image
  delta_x: -5.0e-06
  execute_resolution: 0
  execute_slices: 20
  image_name: working_distance - image
  mask_name: none
  max_attempts: 8
  name: working_distance - image
  sweeping_range:
  - -4.0e-05
  - 4.0e-05
  sweeping_steps: 20
  sweeping_strategy: BasicSweeping
  sweeping_total_cycles: 1
  variable: electron_beam.working_distance
- autofunction: LineAutoFunction
  criterion_name: working_distance - line
  delta_x: 0
  execute_resolution: 0
  execute_slices: 10
  forbidden_sections: 0
  image_name: working_distance - line
  keep_time: 15
  mask_name: none
  max_attempts: 4000000000000000000
  name: working_distance - line
  pre_imaging_delay: 0
  stripes_separate_value: 50
  sweeping_range:
  - -2.0e-05
  - 2.0e-05
  sweeping_steps: 40
  sweeping_strategy: BasicSweeping
  sweeping_total_cycles: 6
  variable: electron_beam.working_distance
contrast_brightness:
  acb_area:
    height: 1
    width: 1
    x: 0
    y: 0
  acb_enabled: true
  allowed_minimal_band: 0.5
  allowed_saturation: 0.01
  mask_name: none
  p_brightness: 10
  p_decrease_contrast: 10
  p_increase_contrast: 10
criterion_calculation:
- border: 0.7
  criterion: frc_criterion
  final_regions_resolution: min
  final_resolution: min
  mask_name: none
  name: image_acquisition
  tile_size: 1.0e-06
- border: 0
  criterion: bandpass_var_criterion
  detail:
  - 1.5e-07
  - 2.5e-07
  final_regions_resolution: min
  final_resolution: min
  mask_name: none
  name: working_distance - line
  tile_size: 0
- border: 0
  criterion: bandpass_criterion
  detail:
  - 1.5e-07
  - 2.5e-07
  final_regions_resolution: min
  final_resolution: min
  mask_name: none
  name: working_distance - image
  tile_size: 0
- border: 0
  criterion: bandpass_criterion
  detail:
  - 8.0e-08
  - 1.5e-07
  final_regions_resolution: min
  final_resolution: min
  mask_name: none
  name: stigX - poke
  tile_size: 0
- border: 0
  criterion: bandpass_criterion
  detail:
  - 8.0e-08
  - 1.5e-07
  final_regions_resolution: min
  final_resolution: min
  mask_name: none
  name: stigY - poke
  tile_size: 0
- border: 0
  criterion: bandpass_criterion
  detail:
  - 8.0e-08
  - 1.5e-07
  final_regions_resolution: min
  final_resolution: min
  mask_name: none
  name: laX - poke
  tile_size: 0
- border: 0
  criterion: bandpass_criterion
  detail:
  - 8.0e-08
  - 1.5e-07
  final_regions_resolution: min
  final_resolution: min
  mask_name: none
  name: laY - poke
  tile_size: 0
- border: 0
  criterion: bandpass_criterion
  detail:
  - 8.0e-08
  - 1.5e-07
  final_regions_resolution: min
  final_resolution: min
  mask_name: none
  name: working_distance - poke
  tile_size: 0
- name: lens_align - TFS
- name: stigmator - TFS
- name: source_tilt - TFS
- name: stigmator - TFS2
- name: working_distance - TFS2
- name: lens_align - TFS_pre
dirs:
  log: D:/Data/251009_biofilm_vol\logs
  output_images: D:/Data/251009_biofilm_vol\images
  project: D:/Data/251009_biofilm_vol
  template_matching: D:/Data/251009_biofilm_vol\template_matching
drift_correction:
  blur: 3
  correction_margin: 2.0e-05
  driftcorr_areas:
  - height: 0.1196
    width: 0.0668
    x: 0.8924
    y: 0.1472
  - height: 0.088
    width: 0.0648
    x: 0.0828
    y: 0.1556
  min_confidence: 0.8
  rescan: 70
  type: template_matching
email:
  password_file: email_password.txt
  receiver: pavel.krep@gmail.com
  sender: pavel.emcf@gmail.com
general:
  additive_beam_shift:
  - 0
  - 0
  error_behaviour:
  - email
  - stop
  library: autoscript
  log_level: 20
  sem_settings_file: microscope_settings.yaml
  variables_to_save:
  - position
  - electron_beam.working_distance
  - electron_beam.stigmator
  - electron_beam.lens_alignment
  - electron_beam.beam_shift
  - electron_beam.detector_contrast
  - electron_beam.detector_brightness
  - electron_beam.dwell_time
image:
- bit_depth: 8
  field_of_view:
  - 5.0e-05
  - 5.0e-05
  images_line_integration: 8
  name: driftcorr
  pixel_size: 2.0e-08
- bit_depth: 16
  dwell: 2.5e-08
  field_of_view:
  - 4.0e-05
  - 3.0e-05
  images_line_integration: 32
  imaging_area:
    height: 0
    width: 0
    x: 0
    y: 0
  name: image_acquisition
  pixel_size: 2.5e-09
- bit_depth: 8
  dwell: 2.5e-08
  field_of_view:
  - 1.66e-05
  - 1.10666666667e-05
  images_line_integration: 64
  imaging_area:
    height: 0.7556666666666667
    width: 0.984
    x: 0.005
    y: 0.20533333333333334
  name: working_distance - line
  resolution:
  - 6144.0
  - 4096.0
- bit_depth: 8
  dwell: 2.5e-08
  images_line_integration: 16
  imaging_area:
    height: 0.286770140428677
    width: 0.3346905537459283
    x: 0.2899022801302932
    y: 0.5402808573540281
  name: working_distance - image
  pixel_size: 5.0e-09
- bit_depth: 8
  dwell: 5.0e-06
  images_line_integration: 1
  imaging_area: &id003
    height: 0.0
    width: 0.0
    x: 0.0
    y: 0.0
  name: stigX - poke
  pixel_size: 1.0e-08
- bit_depth: 8
  dwell: 3.0e-06
  images_line_integration: 1
  imaging_area: &id002
    height: 0.37423312883435583
    width: 0.4603434178250204
    x: 0.34832379394930496
    y: 0.32077125328659073
  name: stigY - poke
  pixel_size: 2.5e-09
- bit_depth: 8
  dwell: 5.0e-06
  images_line_integration: 1
  imaging_area: *id002
  name: laX - poke
  pixel_size: 1.0e-08
- bit_depth: 8
  dwell: 5.0e-06
  images_line_integration: 1
  imaging_area: *id002
  name: laY - poke
  pixel_size: 1.0e-08
- bit_depth: 8
  dwell: 2.0e-07
  images_line_integration: 1
  imaging_area: *id003
  name: working_distance - poke
  pixel_size: 5.0e-09
- brightness: 36.87
  contrast: 63.85
  dwell: 2.5e-08
  images_line_integration: 8
  imaging_area:
    height: 0.4408
    width: 0.3696
    x: 0.2648
    y: 0.0664
  name: lens_align - TFS
- brightness: 36.87
  contrast: 63.85
  dwell: 2.5e-08
  images_line_integration: 16
  imaging_area:
    height: 0.23388671875
    width: 0.15152994791666666
    x: 0.3409830729166667
    y: 0.261474609375
  name: stigmator - TFS
- brightness: 36.87
  contrast: 63.85
  dwell: 5.0e-07
  images_line_integration: 4
  imaging_area:
    height: 0.22173144876325088
    width: 0.2372322899505766
    x: 0.4159802306425041
    y: 0.465547703180212
  name: source_tilt - TFS
- brightness: 36.87
  contrast: 63.85
  dwell: 2.5e-08
  images_line_integration: 1
  imaging_area:
    height: 0.64208984375
    width: 0.4207356770833333
    x: 0.24479166666666666
    y: 0.201904296875
  name: stigmator - TFS2
- brightness: 36.87
  contrast: 63.85
  dwell: 1.0e-07
  images_line_integration: 1
  imaging_area:
    height: 0.908203125
    width: 0.6053059895833334
    x: 0.15592447916666666
    y: 0.03076171875
  name: working_distance - TFS2
- brightness: 36.87
  contrast: 63.85
  dwell: 2.5e-08
  images_line_integration: 128
  imaging_area:
    height: 0.4794921875
    width: 0.3919270833333333
    x: 0.298828125
    y: 0.0048828125
  name: lens_align - TFS_pre
mask:
- downsampling_factor: 4
  fill_holes: true
  iterative_training: false
  mask_image_li: 32
  min_area: 100
  min_fraction: 0.1
  model_path: /home/pavelkrep/data/deepmib_test/seg_exported
  name: mask
  patch_size:
  - 128
  - 128
  threshold: 0.5
  update_mask: true
microscope:
  beam_shift_tolerance: 5.0e-08
  ip_address: 147.251.159.93
  relative_beam_shift_to_stage:
  - 1
  - 1
  stage_tolerance: 1e-7
  stage_trials: 3
milling:
  blur: 2
  direction: 1
  enabled: true
  fiducial_area:
    height: 0.215576171875
    width: 0.12158203125
    x: 0.15120442708333334
    y: 0.239990234375
  fiducial_margin: 3.0e-06
  fiducial_rescan: 3
  fiducial_scans: 1
  fiducial_update: 0.8
  full_image_scans: 1
  milling_area:
    height: 0.552490234375
    width: 0.6525065104166666
    x: 0.3277994791666667
    y: 0.389892578125
  milling_depth: 3.0e-06
  milling_progress: true
  minimal_similarity: 0.75
  pattern_file: Si-ccs
  relocate_pattern: 0
  scanning_frequency: 1
  settings_file: fib_microscope_settings.yaml
  slice_distance: 1.0e-08
  upscale: 4
  variables_to_save:
  - position
  - ion_beam.working_distance
  - ion_beam.beam_shift
  - ion_beam.detector_contrast
  - ion_beam.detector_brightness
  - ion_beam.scan_rotation
