acquisition:
  criterion_name: 'Name of the criterion function used for the resolution calculation of the acquired image. Consult the "criterion_calculation" section for more details.'
  image_name: 'Name of the imaging settings used for image acquisition. Consult the "image" section for more details.'
  imaging_enabled: 'If true, slice imaging is enabled.'
  wd_correction: 'WD increment per each slice.'
  y_correction: 'Y movement increment per each slice.'
autofunction:
  autofunction: 'Autofunction function. Possible values: AutoFunction(basic imaging on the reduced area or full frame),LineAutoFunction(sweeping during imaging), StepAutoFunction(In-line image auto-optimization)'
  criterion_name: 'Autofunction name.'
  delta_x: 'Offset for out of sample focusing on the X-axis.'
  execute_resolution: 'The autofunction is executed if the resolution pass this level.'
  execute_slices: 'Frequency of autofunction execution.'
  image_name: 'The imaging parameters associated with this autofunction - see the image section.'
  mask_name: 'The masking parameters associated with this autofunction - see the mask section.'
  max_attempts: 'If the number of consecutive autofunctions pass this level, the error is invoked.'
  name: 'Title of this autofunction.'
  sweeping_range: 'The range of variable sweep.'
  sweeping_steps: 'Number of steps inside sweeping range.'
  sweeping_strategy: 'Sweeping function. Possible values: BasicSweeping (linear sweeping inside sweeping range), BasicInterleavedSweeping (used in In-line image auto-optimization)'
  sweeping_total_cycles: 'Number of sweeping repeats.'
  variable: 'Sweeping variable.'
  forbidden_sections: 'Sections in scanning sweep that will be excluded from criterion calculation (can be one number or array). Use -1 for including all sections.'
  keep_time: 'Time on staying on one line during scanning sweep.'
  pre_imaging_delay: 'Delay before acquisition of the first section in scanning sweep.'
  stripes_separate_value: 'Separation threshold between black and signal stripes (sum in y).'
contrast_brightness:
  acb_area: 'Defines the imaging area for ACB'
  acb_enabled: 'If true, ACB is enabled.'
  allowed_minimal_band: 'If the histogram width is below this value, the contrast will be increased.'
  allowed_saturation: 'If the ratio of saturated (or zeroed) pixels crosses this value, brightness is corrected. If both, saturated and zeroes pixel are presented, the contrast is decreased.'
  mask_name: 'The masking parameters associated with ACB - see the mask section.'
  p_brightness: 'Multiplication constant between number of forbidden saturated pixels and brightness correction.'
  p_decrease_contrast: 'Multiplication constant between number of forbidden saturated pixels and contrast decrease.'
  p_increase_contrast: 'Multiplication the width of too narrow histogram and and contrast increase.'
criterion_calculation:
  border: 'Ratio of image size that will be excluded from image criterion calculation.'
  criterion: 'Criterion calculation function. Possible parameters: bandpass_criterion, bandpass_var_criterion, fft_criterion, frc_criterion.'
  detail: 'Bandpass parameters (low and high details to filter out).'
  final_regions_resolution: 'Method for calculating final criterion from all masked areas. Accepts numpy functions (min, mean).'
  final_resolution: 'Method for calculating final criterion from tiles. Accepts numpy functions (min, mean).'
  mask_name: 'The masking parameters associated with this autofunction - see the mask section.'
  name: 'Name of this criterion calculation.'
  tile_size: 'Tile size for criterion calculation in pixels.'
dirs:
  log: 'Directory where logs will be saved.'
  output_images: 'Directory where images will be saved.'
  template_matching: 'Directory where templates for drift correction will be saved.'
drift_correction:
  driftcorr_areas: 'Acquisition areas for template matching.'
  min_confidence: 'Similarity threshold. If below, the drift correction won''t be applied.'
  rescan: 'Frequency (no of slices) of template rescan.'
  type: 'Type of drift correction. Possible values: none, template_matching'
email:
  password_file: 'Text file that holds the email password.'
  receiver: 'Email receiver address.'
  sender: 'Email sender address.'
general:
  additive_beam_shift: 'Beam shift added to each slice.'
  error_behaviour: 'Set the behaviour on error. Possible definitions: exception, stop, email, ignore.'
  library: 'Microscope control library. Possible values: virtual, autoscript'
  log_level: 'Logging level. 10 - debug, 20 - info, 30 - warning, 40 - error, 50 - critical'
  sem_settings_file: 'Path to file that holds selected SEM settings.'
  variables_to_save: 'What sem settings will be saved in file and applied every cycle.'
image:
  bit_depth: 'Imaging bit depth.'
  dwell: 'Imaging dwell time.'
  field_of_view: 'Imaging field of view. Resolution and pixel size have higher priority.'
  images_line_integration: 'Imaging line integration.'
  imaging_area: 'Imaging on reduced area.'
  name: 'Title of imaging settings used for image acquisition'
  pixel_size: 'Imaging pixel size.'
  resolution: 'Imaging resolution. Pixel size has higher priority.'
mask:
  downsampling_factor: 'Down-sampling before segmentation.'
  fill_holes: 'Fill holes in segmented image before re-training.'
  iterative_training: 'Train the model after every segmentation.'
  mask_image_li: 'Line integration for mask acquisition.'
  min_area: 'Minimal area for maks usage (use None for disabling).'
  min_fraction: 'Minimal fraction of image must be segmented as mask to proceed calculation.'
  model_path: 'Path to TF model.'
  name: 'Name of this mask application.'
  patch_size: 'Patch size that applied to model.'
  threshold: 'Segmentation threshold.'
  update_mask: 'Grab new image to mask calculation. If False, last image is selected.'
microscope:
  beam_shift_tolerance: 'Relative move between bs and stage move (direction is set by code).'
  ip_address: 'Microscope control server address.'
  relative_beam_shift_to_stage: 'Relative move between beam shift and stage move.'
  stage_tolerance: 'Maximal allowed stage error.'
  stage_trials: 'Number of trials to reach the goal position before raise error.'
milling:
  scanning_frequency: "Number of slices when the fiducial will be localized."
  direction: 'Use -1 to slicing progress upwards, 1 to down direction.'
  enabled: 'If true, milling is enabled.'
  fiducial_area: 'Fiducial position.'
  fiducial_margin: 'The searching area for the fiducial is bigger than defined size.'
  fiducial_rescan: 'Number of scans for fiducial definition. Similarity must be > minimal_similarity.'
  fiducial_update: 'If fiducial similarity drops bellow this limit, it is re-defined.'
  milling_area: 'Milling position.'
  milling_depth: 'Milling Z dimension.'
  milling_enabled: 'Milling enablement.'
  minimal_similarity: 'Similarity threshold. If lower, the fiducial is refused and workflow is stopped.'
  pattern_file: 'Used pattern file.'
  settings_file: 'File name for saving the ion microscope settings.'
  slice_distance: 'Slice thickness.'
  variables_to_save: 'What fib settings will be saved in file and applied every cycle.'